# Site settings
title: DATOS.GOB.MX
email: hola@datos.gob.mx
description: > # this means to ignore newlines until "baseurl:"
  En datos.gob.mx puedes descargar y utilizar libremente datos abiertos
  que el Gobierno de la República genera y recolecta.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000/" # the base hostname & protocol for your site
twitter_username: DatosGobMx
github_username:  mxabierto

# Build settings
markdown: kramdown
gems: [bourbon, jekyll-timeago]
jekyll_timeago:
  depth: 1 # Level of detail
  today: 'hoy'
  yesterday: 'ayer'
  tomorrow: 'mañana'
  and: 'y'
  suffix: ''
  prefix: 'hace'
  suffix_future: 'en'
  prefix_future: ''
  years: 'años'
  year: 'año'
  months: 'meses'
  month: 'mes'
  weeks: 'semanas'
  week: 'semana'
  days: 'dias'
  day: 'dia'
