# Site settings
title: DATOS.GOB.MX
email: hola@datos.gob.mx
description: > # this means to ignore newlines until "baseurl:"
  En datos.gob.mx puedes descargar y utilizar libremente datos abiertos
  que el Gobierno de la República genera y recolecta.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000/dgm" # the base hostname & protocol for your site
twitter_username: DatosGobMx
github_username:  mxabierto

# Build settings
markdown: kramdown
