# Site settings
title: DATOS.GOB.MX
email: hola@datos.gob.mx
description: >
  En datos.gob.mx puedes descargar y utilizar libremente datos abiertos
  que el Gobierno de la República genera y recolecta.
baseurl: "/dgm/"
url: "http://mxabierto.github.io"
twitter_username: DatosGobMx
github_username:  mxabierto

# Build settings
markdown: kramdown
gems: ['bourbon', 'jekyll-timeago']
jekyll_timeago:
  depth: 1 # Level of detail
  today: 'hoy'
  yesterday: 'ayer'
  tomorrow: 'mañana'
  and: 'y'
  suffix: ''
  prefix: 'hace'
  suffix_future: 'en'
  prefix_future: ''
  years: 'años'
  year: 'año'
  months: 'meses'
  month: 'mes'
  weeks: 'semanas'
  week: 'semana'
  days: 'dias'
  day: 'dia'
