# Site settings
title: DATOS.GOB.MX
email: hola@datos.gob.mx
description: >
  En datos.gob.mx puedes descargar y utilizar libremente datos abiertos
  que el Gobierno de la República genera y recolecta.
baseurl: "/dgm/"
url: "http://mxabierto.github.io"
twitter_username: DatosGobMx
github_username:  mxabierto

# Build settings
markdown: kramdown
